# Generated by Django 2.2.1 on 2019-05-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
                ('client_street_number', models.IntegerField()),
                ('client_street_name', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(max_length=100)),
                ('client_zip_code', models.IntegerField()),
                ('client_telephone', models.IntegerField()),
                ('client_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=100)),
                ('ticket_cost', models.IntegerField()),
                ('ticket_season', models.CharField(max_length=100)),
                ('ticket_content_image', models.ImageField(upload_to='')),
                ('ticket_content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='davey_main.Client')),
            ],
        ),
    ]
