# Generated by Django 2.2.1 on 2019-05-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davey_main', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arborist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arb_name_first', models.CharField(max_length=100)),
                ('arb_name_last', models.CharField(max_length=100)),
                ('abr_zip', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='davey_main.Arborist'),
        ),
    ]
