# Generated by Django 2.2.1 on 2019-05-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davey_main', '0003_auto_20190521_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='davey_main.Client'),
        ),
    ]
