# Generated by Django 2.2.1 on 2019-06-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davey_main', '0004_auto_20190521_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_telephone',
            field=models.CharField(max_length=20),
        ),
    ]
